description: Creating an app deployment will pull the latest changes from your repository
  and schedule a new deployment for your app.
operationId: create_deployment
parameters:
- description: The app ID
  in: path
  name: app_id
  required: true
  schema:
    type: string
requestBody:
  content:
    application/json:
      schema:
        $ref: models/apps_create_deployment_request.gen.yml
  required: true
  x-originalParamName: body
responses:
  "200":
    content:
      application/json:
        schema:
          $ref: models/apps_deployment_response.gen.yml
    description: A successful response.
    headers:
      ratelimit-limit:
        $ref: ../../shared/headers.yml#/ratelimit-limit
      ratelimit-remaining:
        $ref: ../../shared/headers.yml#/ratelimit-remaining
      ratelimit-reset:
        $ref: ../../shared/headers.yml#/ratelimit-reset
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
summary: Create an App Deployment
tags:
- Apps
