description: List all deployments of an app.
operationId: list_deployments
parameters:
- description: The app ID
  in: path
  name: app_id
  required: true
  schema:
    type: string
- $ref: ../../shared/parameters.yml#/page
- $ref: ../../shared/parameters.yml#/per_page
responses:
  "200":
    content:
      application/json:
        schema:
          $ref: models/apps_deployments_response.gen.yml
    description: A successful response.
    headers:
      ratelimit-limit:
        $ref: ../../shared/headers.yml#/ratelimit-limit
      ratelimit-remaining:
        $ref: ../../shared/headers.yml#/ratelimit-remaining
      ratelimit-reset:
        $ref: ../../shared/headers.yml#/ratelimit-reset
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
summary: List App Deployments
tags:
- Apps
