openapi: 3.0.0
info:
  title: DigitalOcean API
  version: '2.0'
  description: 'The DigitalOcean API allows you to manage Droplets and resources within the DigitalOcean cloud in a simple, programmatic way using conventional HTTP requests.'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: DigitalOcean API Team
    email: api-engineering@digitalocean.com
  termsOfService: 'https://www.digitalocean.com/legal/terms-of-service-agreement/'
servers:
  - url: 'https://api.digitalocean.com/v2'
    description: production
tags:
  - name: Account
    description: Provides information about your current account.
  - name: Images
    description: >-
      A DigitalOcean image can be used to create a Droplet and may come in a number of flavors.
  - name: SSH Keys
    description: Manage SSH keys available on your account.
paths:
  /account:
    get:
      $ref: 'resources/account/get_user_information.yml'
  /account/keys:
    get:
      $ref: 'resources/ssh_keys/list_all_keys.yml'
  /images:
    get: 
      $ref: 'resources/images/list_images.yml'
  /images/{image_identifier}:
    get:
      $ref: 'resources/images/get_image.yml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []