type: object

properties:
  server:
    type: string
    example: https://bd5f5959-5e1e-4205-a714-a914373942af.k8s.ondigitalocean.com
    description: The URL used to access the cluster API server.

  certificate_authority_data:
    type: string
    example: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUxCUUF3TXpFVk1CTUdBMVVFQ2ftTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dUSREERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHhPREV4TVRVeApOakF3TWpCYUZ3MHpPREV4TVRVeE5qQXdNakJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDK2Z0L05Nd3pNaUxFZlFvTFU2bDgrY0hMbWttZFVKdjl4SmlhZUpIU0dZOGhPZFVEZQpGd1Zoc0pDTnVFWkpJUFh5Y0orcGpkU3pYc1lFSE03WVNKWk9xNkdaYThPMnZHUlJjN2ZQaUFJaFBRK0ZpUmYzCmRhMHNIUkZlM2hCTmU5ZE5SeTliQ2VCSTRSUlQrSEwzRFR3L2I5KytmRkdZQkRoVTEvTTZUWWRhUHR3WU0rdWgKb1pKcWJZVGJZZTFhb3R1ekdnYUpXaXRhdFdHdnNJYU8xYWthdkh0WEIOOHFxa2lPemdrSDdvd3RVY3JYM05iawozdmlVeFU4TW40MmlJaGFyeHNvTnlwdGhHOWZLMi9OdVdKTXJJS2R0Mzhwc0tkdDBFbng0MWg5K0dsMjUzMzhWCk1mdjBDVDF6SG1JanYwblIrakNkcFd0eFVLRyt0YjYzZFhNbkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNQMmJrOXJiUGJpQnZOd1Z1NQpUL0dwTFdvOTdEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEVjFMSGZyc1JiYVdONHE5SnBFVDMxMlluRDZ6Cm5rM3BpU1ZSYVEvM09qWG8wdHJ6Z2N4KzlVTUQxeDRHODI1RnYxc0ROWUExZEhFc2dHUmNyRkVmdGZJQWUrUVYKTitOR3NMRnQrOGZrWHdnUlpoNEU4ZUJsSVlrdEprOWptMzFMT25vaDJYZno0aGs3VmZwYkdvVVlsbmVoak1JZApiL3ZMUk05Y2EwVTJlYTB5OTNveE5pdU9PcXdrZGFjU1orczJtb3JNdGZxc3VRSzRKZDA3SENIbUFIeWpXT2k4ClVOQVUyTnZnSnBKY2RiZ3VzN2I5S3ppR1ZERklFUk04cEo4U1Nob1ZvVFFJd3d5Y2xVTU9EUUJreFFHOHNVRk8KRDE3ZjRod1dNbW5qVHY2MEJBM0dxaTZRcjdsWVFSL3drSEtQcnZjMjhoNXB0NndPWEY1b1M4OUZkUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    description: A base64 encoding of bytes representing the certificate
      authority data for accessing the cluster.

  client_certificate_data:
    type: string
    deprecated: true
    nullable: true
    example: null
    description: |
      A base64 encoding of bytes representing the x509 client
      certificate data for access the cluster. This is only returned for clusters
      without support for token-based authentication.

      Newly created Kubernetes clusters do not return credentials using
      certificate-based authentication. For additional information,
      [see here](https://www.digitalocean.com/docs/kubernetes/how-to/connect-to-cluster/#authenticate).

  client_key_data:
    type: string
    deprecated: true
    nullable: true
    example: null
    description: |
      A base64 encoding of bytes representing the x509 client key
      data for access the cluster. This is only returned for clusters without
      support for token-based authentication.

      Newly created Kubernetes clusters do not return credentials using
      certificate-based authentication. For additional information,
      [see here](https://www.digitalocean.com/docs/kubernetes/how-to/connect-to-cluster/#authenticate).

  token:
    type: string
    example: b7d03a6947b217efb6f3ec3bd3504582
    description: An access token used to authenticate with the cluster. This is
      only returned for clusters with support for token-based authentication.

  expires_at:
    type: string
    format: date-time
    example: 2019-11-09T11:50:28.889080521Z
    description: A time value given in ISO8601 combined date and time format
      that represents when the access token expires.
