DropletId:
  in: path
  name: droplet_id
  description: A unique identifier for a Droplet instance.
  required: true
  schema:
    type: integer
    minimum: 1

DropletTagName:
  in: query
  name: tag_name
  description: Used to filter Droplets by a specific tag.
  required: false
  schema:
    type: string
  example: env:prod
