DropletId:
  in: path
  name: droplet_id
  description: A unique identifier for a Droplet instance.
  required: true
  schema:
    type: integer
    minimum: 1

DropletTagName:
  in: query
  name: tag_name
  description: Used to filter Droplets by a specific tag.
  required: false
  schema:
    type: string
  example: env:prod

DropletDeleteTagName:
  in: query
  name: tag_name
  description: Specifies Droplets to be deleted by tag.
  required: true
  schema:
    type: string
  example: env:test

X-Dangerous:
  in: header
  name: X-Dangerous
  description: Acknowledge this action will destroy the Droplet and all
    associated resources and _can not_ be reverse.
  schema:
    type: boolean
  example: true
  required: true
