properties:
  error_steps:
    format: int32
    title: Number of unsuccessful steps
    type: integer
  pending_steps:
    format: int32
    title: Number of pending steps
    type: integer
  running_steps:
    format: int32
    title: Number of currently running steps
    type: integer
  steps:
    items:
      $ref: apps_deployment_progress_step.gen.yml
    title: The deployment's steps
    type: array
  success_steps:
    format: int32
    title: Number of successful steps
    type: integer
  summary_steps:
    items:
      $ref: apps_deployment_progress_step.gen.yml
    title: A flattened summary of the steps
    type: array
  total_steps:
    format: int32
    title: Total number of steps
    type: integer
type: object
