properties:
  app_id:
    title: The app ID
    type: string
  force_build:
    format: boolean
    title: Indicates whether to force a build of app from source even if an existing
      cached build is suitable for re-use
    type: boolean
required:
- app_id
type: object
