KubernetesClustersAll:
  value:
    kubernetes_clusters:
    - id: bd5f5959-5e1e-4205-a714-a914373942af
      name: prod-cluster-01
      region: nyc1
      version: 1.18.6-do.0
      cluster_subnet: 10.244.0.0/16
      service_subnet: 10.245.0.0/16
      vpc_uuid: c33931f2-a26a-4e61-b85c-4e95a2ec431b
      ipv4: 68.183.121.157
      endpoint: https://bd5f5959-5e1e-4205-a714-a914373942af.k8s.ondigitalocean.com
      tags:
      - production
      - web-team
      - k8s
      - k8s:bd5f5959-5e1e-4205-a714-a914373942af
      node_pools:
      - id: cdda885e-7663-40c8-bc74-3a036c66545d
        name: frontend-pool
        size: s-1vcpu-2gb
        count: 3
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels: null
        auto_scale: false
        min_nodes: 0
        max_nodes: 0
        nodes:
        - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
          name: adoring-newton-3niq
          status:
            state: provisioning
          droplet_id: '205545370'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
          name: adoring-newton-3nim
          status:
            state: provisioning
          droplet_id: '205545371'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: e46e8d07-f58f-4ff1-9737-97246364400e
          name: adoring-newton-3ni7
          status:
            state: provisioning
          droplet_id: '205545372'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      - id: f49f4379-7e7f-4af5-aeb6-0354bd840778
        name: backend-pool
        size: g-4vcpu-16gb
        count: 2
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels:
          service: backend
          priority: high
        auto_scale: true
        min_nodes: 2
        max_nodes: 5
        nodes:
        - id: 3385619f-8ec3-42ba-bb23-8d21b8ba7518
          name: affectionate-nightingale-3nif
          status:
            state: provisioning
          droplet_id: '205545373'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: 4b8f60ff-ba06-4523-a6a4-b8148244c7e6
          name: affectionate-nightingale-3niy
          status:
            state: provisioning
          droplet_id: '205545374'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      maintenance_policy:
        start_time: '00:00'
        duration: 4h0m0s
        day: any
      auto_upgrade: false
      status:
        state: provisioning
        message: provisioning
      created_at: '2018-11-15T16:00:11Z'
      updated_at: '2018-11-15T16:00:11Z'
      surge_upgrade: false
    meta:
      total: 1

KubernetesClustersCreateBasicResponse:
  value:
    kubernetes_cluster:
      id: bd5f5959-5e1e-4205-a714-a914373942af
      name: prod-cluster-01
      region: nyc1
      version: 1.18.6-do.0
      cluster_subnet: 10.244.0.0/16
      service_subnet: 10.245.0.0/16
      vpc_uuid: c33931f2-a26a-4e61-b85c-4e95a2ec431b
      ipv4: ' '
      endpoint: ' '
      tags:
      - k8s
      - k8s:bd5f5959-5e1e-4205-a714-a914373942af
      node_pools:
      - id: cdda885e-7663-40c8-bc74-3a036c66545d
        name: worker-pool
        size: s-1vcpu-2gb
        count: 3
        tags:
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels: null
        auto_scale: false
        min_nodes: 0
        max_nodes: 0
        nodes:
        - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
          name: ' '
          status:
            state: provisioning
          droplet_id: ' '
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
          name: ' '
          status:
            state: provisioning
          droplet_id: ' '
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: e46e8d07-f58f-4ff1-9737-97246364400e
          name: ' '
          status:
            state: provisioning
          droplet_id: ' '
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      maintenance_policy:
        start_time: '00:00'
        duration: 4h0m0s
        day: any
      auto_upgrade: false
      status:
        state: provisioning
        message: provisioning
      created_at: '2018-11-15T16:00:11Z'
      updated_at: '2018-11-15T16:00:11Z'
      surge_upgrade: false

KubernetesClustersMultiPoolResponse:
  value:
    kubernetes_clusters:
      id: bd5f5959-5e1e-4205-a714-a914373942af
      name: prod-cluster-01
      region: nyc1
      version: 1.18.6-do.0
      cluster_subnet: 10.244.0.0/16
      service_subnet: 10.245.0.0/16
      vpc_uuid: c33931f2-a26a-4e61-b85c-4e95a2ec431b
      ipv4: ' '
      endpoint: ' '
      tags:
      - production
      - web-team
      - k8s
      - k8s:bd5f5959-5e1e-4205-a714-a914373942af
      node_pools:
      - id: cdda885e-7663-40c8-bc74-3a036c66545d
        name: frontend-pool
        size: s-1vcpu-2gb
        count: 3
        tags:
        - production
        - web-team
        - frontend
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels: null
        auto_scale: false
        min_nodes: 0
        max_nodes: 0
        nodes:
        - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
          name: ' '
          status:
            state: provisioning
          droplet_id: ' '
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
          name: ' '
          status:
            state: provisioning
          droplet_id: ' '
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: e46e8d07-f58f-4ff1-9737-97246364400e
          name: ' '
          status:
            state: provisioning
          droplet_id: ' '
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      - id: f49f4379-7e7f-4af5-aeb6-0354bd840778
        name: backend-pool
        size: g-4vcpu-16gb
        count: 2
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels:
          service: backend
          priority: high
        auto_scale: true
        min_nodes: 2
        max_nodes: 5
        nodes:
        - id: 3385619f-8ec3-42ba-bb23-8d21b8ba7518
          name: ' '
          status:
            state: provisioning
          droplet_id: ' '
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: 4b8f60ff-ba06-4523-a6a4-b8148244c7e6
          name: ' '
          status:
            state: provisioning
          droplet_id: ' '
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      maintenance_policy:
        start_time: '12:00'
        duration: 4h0m0s
        day: any
      auto_upgrade: false
      status:
        state: provisioning
        message: provisioning
      created_at: '2018-11-15T16:00:11Z'
      updated_at: '2018-11-15T16:00:11Z'
      surge_upgrade: false
