lang: Go
source: |-
  import (
      "context"
      "github.com/digitalocean/godo"
  )

  func main() {
      pat := "mytoken"

      client := godo.NewFromToken(pat)
      ctx := context.TODO()

      createRequest := &godo.KubernetesNodePoolCreateRequest{
          Name:  "pool-02",
          Size:  "s-2vcpu-4gb",
          Count: 1,
          Tags:  []string{"web"},
          Labels:  map[string]string{"service": "web", "priority": "high"},
      }

      nodePool, _, err := client.Kubernetes.CreateNodePool(ctx, "bd5f5959-5e1e-4205-a714-a914373942af", createRequest)
  }
