lang: Go
source: |-
  import (
      "context"
      "github.com/digitalocean/godo"
  )

  func main() {
      pat := "mytoken"

      client := godo.NewFromToken(pat)
      ctx := context.TODO()

      _, err := client.Kubernetes.DeleteNodePool(ctx, "bd5f5959-5e1e-4205-a714-a914373942af", "86c9bc8c-b2c3-4d40-8000-b0c7bee27305")
  }
