lang: Go
source: |-
  import (
      "context"
      "os"

      "github.com/digitalocean/godo"
  )

  func main() {
      pat := os.Getenv("DIGITALOCEAN_TOKEN")

      client := godo.NewFromToken(pat)
      ctx := context.TODO()

      cluster, _, err := client.Kubernetes.Get(ctx, "bd5f5959-5e1e-4205-a714-a914373942af")
  }
