lang: Go
source: |-
  import (
      "context"
      "github.com/digitalocean/godo"
  )

  func main() {
      pat := "mytoken"

      client := godo.NewFromToken(pat)
      ctx := context.TODO()

      credentials, _, err := client.Kubernetes.GetCredentials(ctx, "bd5f5959-5e1e-4205-a714-a914373942af")
  }
