lang: Go
source: |-
  import (
      "context"
      "github.com/digitalocean/godo"
  )

  func main() {
      pat := "mytoken"

      client := godo.NewFromToken(pat)
      ctx := context.TODO()

      upgradeRequest := &godo.KubernetesClusterUpgradeRequest{
      	VersionSlug: "1.12.3-do.1",
      }
  }
