lang: Ruby
source: |-
  require 'droplet_kit'
  token = '16f79fc8cd5adcfe528a0994311fa63cc877737b385b6ff7d12ed6684ba4fef5'
  client = DropletKit::Client.new(access_token: token)

  client.kubernetes_clusters.find(id: 'bd5f5959-5e1e-4205-a714-a914373942af')
