operationId: add_registry

summary: Add Container Registry to Kubernetes Clusters

description: To integrate the container registry with Kubernetes clusters, send
  a POST request to `/v2/kubernetes/registry`.

tags:
  - Kubernetes

requestBody:
  content:
    application/json:
      schema:
        $ref: 'models/cluster_registries.yml'

responses:
  '204':
    $ref: '../../shared/responses/no_content.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'