operationId: delete_kubernetes_node

summary: Delete a Node in a Kubernetes Cluster

description: |
  To delete a single node in a pool, send a DELETE request to
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/node_pools/$NODE_POOL_ID/nodes/$NODE_ID`.

  Appending the `skip_drain=1` query parameter to the request causes node
  draining to be skipped. Omitting the query parameter or setting its value to
  `0` carries out draining prior to deletion.

  Appending the `replace=1` query parameter to the request causes the node to
  be replaced by a new one after deletion. Omitting the query parameter or
  setting its value to `0` deletes without replacement.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/KubernetesClusterId'
  - $ref: 'parameters.yml#/KubernetesNodePoolId'
  - $ref: 'parameters.yml#/KubernetesNodeId'
  - $ref: 'parameters.yml#/KubernetesNodeSkipDrain'
  - $ref: 'parameters.yml#/KubernetesNodeReplace'

responses:
  '202':
    $ref: '../../shared/responses/accepted.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'
