operationId: delete_kubernetes_node_pool

summary: Delete a Node Pool in a Kubernetes Cluster

description: |
  To delete a node pool, send a DELETE request to
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/node_pools/$NODE_POOL_ID`.

  A 204 status code with no body will be returned in response to a successful
  request. Nodes in the pool will subsequently be drained and deleted.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/KubernetesClusterId'
  - $ref: 'parameters.yml#/KubernetesNodePoolId'

responses:
  '204':
    $ref: '../../shared/responses/no_content.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'
