KubernetesClusterId:
  in: path
  name: cluster_id
  description: A unique ID that can be used to reference a Kubernetes cluster.
  required: true
  schema:
    type: string
    minimum: 1
  example: bd5f5959-5e1e-4205-a714-a914373942af

KubernetesNodePoolId:
  in: path
  name: node_pool_id
  description: A unique ID that can be used to reference a Kubernetes node pool.
  required: true
  schema:
    type: string
    minimum: 1
  example: cdda885e-7663-40c8-bc74-3a036c66545d

KubernetesExpirySeconds:
  in: query
  name: expiry_seconds
  required: false
  description: The duration in seconds that the returned Kubernetes credentials
   will be valid. If not set or 0, the credentials will have a 7 day expiry.
  schema:
    type: integer
    minimum: 0
    default: 0
  example: 300
