operationId: retrievenode_pool

summary: Retrieve a Node Pool for a Kubernetes Cluster

description: |
  To show information about a specific node pool in a Kubernetes cluster, send
  a GET request to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/node_pools/$NODE_POOL_ID`.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'
  - $ref: 'parameters.yml#/kubernetes_node_pool_id'

responses:
  '200':
    $ref: 'responses/existing_node_pool.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'