operationId: update_kubernetes_cluster

summary: Update a Kubernetes Cluster

description: |
  To update a Kubernetes cluster, send a PUT request to
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID` and specify one or more of the
  attributes below.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/KubernetesClusterId'

requestBody:
  required: true

  content:
    application/json:
      schema:
        $ref: 'models/cluster_update.yml'

responses:
  '200':
    $ref: 'responses/updated_cluster.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'