VolumeId:
  name: volume_id
  in: path
  description: The unique identifier for the snapshot.
  required: true
  schema:
    type: string
    format: uuid
  example: 7724db7c-e098-11e5-b522-000f53304e51

VolumeName:
  name: name
  in: query
  description: The volume's name.
  schema:
    type: string
  example: example

VolumeSnapshotId:
  name: snapshot_id
  in: path
  description: The unique identifier for the snapshot.
  schema:
    type: string
  required: true
  example: fbe805e8-866b-11e6-96bf-000f53315a41