name: Generate Preview

on:
  pull_request:

jobs:
  generate-preview:
    name: Bundle and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: make bundle
      - name: Upload PR spec
        run: >-
          aws s3 cp tests/openapi-bundled.yaml 
          s3://api-engineering/spec-ci/previews/${{ github.event.number }}-spec.yaml
          --endpoint=${{ env.SPACES_ENDPOINT }} 
          --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_SECRET }}
          AWS_DEFAULT_OUTPUT: json
          SPACES_ENDPOINT: https://nyc3.digitaloceanspaces.com
      - name: Update commit
        uses: ouzi-dev/commit-status-updater@v1.0.7
        with: 
          description: "ReDoc Preview Ready"
          status: "${{ job.status }}"
          pendingComment: "Publishing preview"
          successComment: "Preview ready"
          url: "https://api-engineering.nyc3.digitaloceanspaces.com/spec-ci/redoc-index.html?pr=${{ github.event.number }}"
