name: Run Spectral

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  lint:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run contract validation
        run: make lint