name: ReDoc Index PR
# This workflow uploads a copy of the `docs-preview/redoc-index.html` to the
# team spaces directory when a change is detected on the file.
# For PRs, the uploaded file name will be suffixed with the PR number.
# e.g. `docs-preview/redoc-index-pr-123.html`

on:
  pull_request_target:
    paths:
      - 'docs-preview/redoc-index.html'

jobs:

  upload-index-preview:
    name: Upload Index Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload index to spaces
        env:
          REDOC_INDEX_FILENAME: redoc-index-pr-${{ github.event.number }}.html
          SPACES_PATH: ${{ secrets.SPACES_PATH }}
        run: >-
          aws s3 cp docs-preview/redoc-index.html 
          s3://$SPACES_PATH/$REDOC_INDEX_FILENAME
          --endpoint=$SPACES_ENDPOINT
          --acl public-read

      - name: Comment on PR with preview link
        env:
          PREVIEW_URL: https://api-engineering.nyc3.digitaloceanspaces.com/spec-ci/$REDOC_INDEX_FILENAME
        run: >-
          gh pr review ${{github.event.number}} --comment -b "ReDoc Index preview is ready. View it [here]($PREVIEW_URL)" 
