name: Spec PR
# This workflow uploads a copy of the spec with the respective changes in the PR
# to the team spaces.
# The name of the uplaoded file will be prefixed with the PR number.
# e.g. `spec-ci/previews/123-spec.yaml

on:
  pull_request_target:
    paths:
      - 'specification/**'
      - 'spectral/**'

jobs:

  lint:
    name: Validate spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: make lint

  generate-preview:
    name: Generate Preview
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Bundle
        run: make bundle

      - uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: tests/openapi-bundled.yaml

      - name: Upload PR spec
        run: >-
          aws s3 cp tests/openapi-bundled.yaml 
          s3://$SPACES_PATH/previews/${{ github.event.number }}-spec.yaml
          --endpoint=$SPACES_ENDPOINT 
          --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_SECRET }}
          AWS_DEFAULT_OUTPUT: json
          SPACES_ENDPOINT: https://nyc3.digitaloceanspaces.com

      - name: Comment on PR with preview link
        env:
          PREVIEW_URL: https://api-engineering.nyc3.digitaloceanspaces.com/spec-ci/redoc-index.html?pr=${{ github.event.number }}
        run: >-
          gh pr review ${{github.event.number}} --comment -b "Spec preview is ready. View it [here]($PREVIEW_URL)" 
